language: python

python:
  - "2.7"

cache: pip
install:
  - pip install -r requirements.txt
  - python -c "import nltk; nltk.download('stopwords');nltk.download('punkt');nltk.download('wordnet');"
  - python -m spacy download en 
  - python -c "import spacy; spacy.load('en')"

script:
  - pytest
